{
 "title": "HDFS-DataNode",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(hadoop_hdfs_datanode_system_cpu_load, cluster)"
   },
   {
    "name": "datanode",
    "query": "label_values(hadoop_hdfs_datanode_system_cpu_load{cluster=\"$cluster\"}, _target)"
   }
  ]
 },
 "panels": [
  {
   "title": "datanode_capacity",
   "type": "graph",
   "description": "Current raw capacity of DataNode in bytes",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_capacity{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_dfs_used",
   "type": "graph",
   "description": "Current space used by DataNodes for DFS purposes in bytes",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_dfs_used{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_remaining",
   "type": "graph",
   "description": "Current remaining capacity in bytes",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_remaining{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_failed_volumes",
   "type": "graph",
   "description": "Total number of failed volumes",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_failed_volumes{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_volume_state",
   "type": "table",
   "description": "Volume infomation in each path and in each mode",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_volume_state{state=~'usedSpace|freeSpace', cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "datanode_bytes_written_rate",
   "type": "graph",
   "description": "Total rate of bytes written to DataNode",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hdfs_datanode_bytes_written{cluster=\"$cluster\", _target=~\"$datanode\"}[2m])",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_bytes_read_rate",
   "type": "graph",
   "description": "Total rate of bytes read from DataNode",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hdfs_datanode_bytes_read{cluster=\"$cluster\", _target=~\"$datanode\"}[2m])",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_total_write_time",
   "type": "graph",
   "description": "Total number of milliseconds spent on write operation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_total_write_time{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_total_read_time",
   "type": "graph",
   "description": "Total number of milliseconds spent on read operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_total_read_time{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_block_operations_total_rate",
   "type": "graph",
   "description": "Total number of blocks in different oprations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hdfs_datanode_block_operations_total{cluster=\"$cluster\", _target=~\"$datanode\"}[2m])",
     "legendFormat": "{{_target}}_{{oper}}"
    }
   ]
  },
  {
   "title": "datanode_from_client_total_rate",
   "type": "graph",
   "description": "Total number of each operations from different client",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hdfs_datanode_from_client_total{cluster=\"$cluster\", _target=~\"$datanode\"}[2m])",
     "legendFormat": "{{_target}}_{{client}}_{{oper}}"
    }
   ]
  },
  {
   "title": "datanode_jvm_gc_exceeded_threshold_total",
   "type": "graph",
   "description": "Number of times that the GC threshold is exceeded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_jvm_gc_exceeded_threshold_total{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}_{{type}}"
    }
   ]
  },
  {
   "title": "datanode_jvm_gc_total_extra_sleep_time",
   "type": "graph",
   "description": "Total GC extra sleep time in msec.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_jvm_gc_total_extra_sleep_time{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_jvm_gc_count",
   "type": "graph",
   "description": "GC count of each type GC.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_jvm_gc_count{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}_{{type}}"
    }
   ]
  },
  {
   "title": "datanode_jvm_gc_time_milliseconds",
   "type": "graph",
   "description": "Each type GC time in milliseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_jvm_gc_time_milliseconds{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}_{{type}}"
    }
   ]
  },
  {
   "title": "datanode_fsync_count",
   "type": "graph",
   "description": "Total number of fsync",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_fsync_count{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "hadoop_hdfs_datanode_fsync_nanos_num_ops",
   "type": "graph",
   "description": "Total number of fsync",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_fsync_nanos_num_ops{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_send_data_packet_transfer_nanos_num_ops",
   "type": "graph",
   "description": "Total rate of sending packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hdfs_datanode_send_data_packet_transfer_nanos_num_ops{cluster=\"$cluster\", _target=~\"$datanode\"}[2m])",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_send_data_packet_transfer_nanos_avg_time",
   "type": "graph",
   "description": "Average transfer time of sending packets in nanoseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_send_data_packet_transfer_nanos_avg_time{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_send_data_packet_blocked_on_network_nanos_num_ops",
   "type": "graph",
   "description": "Total rate of sending packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hdfs_datanode_send_data_packet_blocked_on_network_nanos_num_ops{cluster=\"$cluster\", _target=~\"$datanode\"}[2m])",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_send_data_packet_blocked_on_network_nanos_avg_time",
   "type": "graph",
   "description": "Average waiting time of sending packets in nanoseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_send_data_packet_blocked_on_network_nanos_avg_time{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "hadoop_hdfs_datanode_fsync_nanos_avg_time",
   "type": "graph",
   "description": "Average fsync time in nanoseconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_datanode_fsync_nanos_avg_time{cluster=\"$cluster\", _target=~\"$datanode\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "datanode_datanode_network_errors",
   "type": "graph",
   "description": "Total rate of datanode network error",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hdfs_datanode_datanode_network_errors{cluster=\"$cluster\", _target=~\"$datanode\"}[2m])",
     "legendFormat": "{{_target}}"
    }
   ]
  }
 ]
}