{
 "title": "YARN - ResourceManager",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "resourcemanager_nodemanager_total",
   "type": "bargauge",
   "description": "Current number of NodeManagers in each status",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_nodemanager_total",
     "legendFormat": "{{cluster}}__{{status}}"
    }
   ]
  },
  {
   "title": "resourcemanager_node_state",
   "type": "graph",
   "description": "State of the host - valid values are: NEW, RUNNING, UNHEALTHY, DECOMMISSIONED, LOST, REBOOTED",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_node_state",
     "legendFormat": "{{cluster}}_{{host}}"
    }
   ]
  },
  {
   "title": "State of the node",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "content": "State of the node - valid values are: \n+ 1: NEW\n+ 2: RUNNING\n+ 3: UNHEALTHY\n+ 4: DECOMMISSIONED\n+ 5: LOST\n+ 6: REBOOTED\n\n\n\n"
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_memory_in_mb{user != \"dr.who\", user = \"-\", status !~ \"MaxShare|MinShare|FairShare\"}",
     "legendFormat": "{{cluster}}_{{queue}}_{{user}}_{{status}}"
    }
   ]
  },
  {
   "title": "resourcemanager_node_memory_used",
   "type": "graph",
   "description": "The total amount of memory currently used on the host (in MB)",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_node_memory_used_mb",
     "legendFormat": "{{cluster}}_{{host}}"
    }
   ]
  },
  {
   "title": "resourcemanager_node_memory_available",
   "type": "graph",
   "description": "The total amount of memory currently available on the host (in MB)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_node_memory_available_mb",
     "legendFormat": "{{cluster}}_{{host}}"
    }
   ]
  },
  {
   "title": "VCores",
   "type": "graph",
   "description": "Current allocated CPU in virtual cores.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_vcore_count{user != \"dr.who\", user = \"-\", status !~ \"MaxShare|MinShare|FairShare\"}",
     "legendFormat": "{{cluster}}_{{queue}}_{{user}}_{{status}}"
    }
   ]
  },
  {
   "title": "nodemanager_allocated_vcores",
   "type": "graph",
   "description": "Current allocated CPU in virtual cores.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_allocated_vcores",
     "legendFormat": "{{cluster}}_{{host}}"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "graph",
   "description": "Applications",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_application_count{user != \"dr.who\", user = \"-\", status !~ \"Completed|Submitted|MaxShare|MinShare|FairShare\"}",
     "legendFormat": "{{cluster}}_{{queue}}_{{user}}_{{status}}"
    }
   ]
  },
  {
   "title": "resourcemanager_running_app_total",
   "type": "graph",
   "description": " Current number of running applications in each elapsed time ( < 60min, 60min < x < 300min, 300min < x < 1440min and x > 1440min )",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_running_app_total{user != \"dr.who\", user != \"-\"}",
     "legendFormat": "{{cluster}}_{{queue}}_{{user}}_{{elapsed_time}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "description": "Containers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_container_count{user != \"dr.who\", user = \"-\", status !~ \"MaxShare|MinShare|FairShare\"}",
     "legendFormat": "{{cluster}}_{{queue}}_{{user}}_{{status}}"
    }
   ]
  },
  {
   "title": "resourcemanager_node_containers_total",
   "type": "graph",
   "description": "Total number of containers currently running on the host",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_resourcemanager_node_containers_total",
     "legendFormat": "{{cluster}}_{{host}}"
    }
   ]
  }
 ]
}