{
 "title": "YARN - NodeManager",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(hadoop_yarn_nodemanager_available_vcores, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(hadoop_yarn_nodemanager_available_vcores, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "container_count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_container_count{cluster=\"${cluster}\", host=\"${node}\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "running_container_count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_container_count{cluster=\"${cluster}\", host=\"${node}\", status=\"Running\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "allocated_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_allocated_gb > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "available_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_available_gb",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "allocated_vcores",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_allocated_vcores{cluster=\"${cluster}\", host=\"${node}\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "available_vcores",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_available_vcores{cluster=\"${cluster}\", host=\"${node}\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "container_launch_per_minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_yarn_nodemanager_container_launch_duration_num_ops{cluster=\"${cluster}\", host=\"${node}\"}[2m])*60",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "container_launch_duration_avg_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_container_launch_duration_avg_time{cluster=\"${cluster}\", host=\"${node}\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "nodemanager_shuffle_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_shuffle_connections{cluster=\"$cluster\", host=\"${node}\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "nodemanager_shuffle_output_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_shuffle_output_bytes",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "nodemanager_shuffle_outputs_failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_shuffle_outputs_failed",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "nodemanager_shuffle_outputs_ok",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_yarn_nodemanager_shuffle_outputs_ok",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}